env:
  global:
    secure: "XSDqVEb9qwXDpifbNaFL+iEXnMpdHp+IW2/i11QmCPmPY/CtTv1UDqq32q6mV65Pbdlynsoia8Ld1Rt/6j8JbRZEHKF6LlKfeLCSMa1yOE38lSHAJ33eQ1aAUepqmA/Ex8UBpSlyVQXaO76hjQYCYKOsvx6L07CpCFRzUPJ1Vkg="

sudo: false

language: java

jdk:
  - openjdk6

branches:
  only:
    - master

script: mvn -f com.codeaffine.osgi.testsuite.releng/pom.xml clean verify

after_success: 
  - chmod a+x .travis-deploy.sh
  - ./.travis-deploy.sh

after_failure:
  - cat com.codeaffine.osgi.testsuite.test/target/surefire-reports/*.txt
